exports.messages = {
  FIRST_NAME_REQUIRED: "First name is required",
  FIRST_NAME_INVALID_LENGTH: "Maximum 50 characters allowed",
  LAST_NAME_REQUIRED: "Last name is required",
  LAST_NAME_INVALID_LENGTH: "Maximum 50 characters allowed",
  EMAIL_INVALID: "Please provide a valid email address",
  EMAIL_REQUIRED: "Email is required",
  DOB_REQUIRED: "Date of birth is required",
  DOB_MIN_LIMIT: "Minimum age requirement of 18 years",
  DOB_MAX_LIMIT: "Maximum date range greater than 1900",
  CAPTCHA_REQUIRED: "Captcha is required",
  ROLE_REQUIRED: "Role is required",
  INVALID_SOURCE_CURRENCY: "Invalid source currency",
  INVALID_DESTINATION_CURRENCY: "Invalid destination currency",
  /////////
  ID_REQUIRED: "Id is required",
  RECIPIENT_ID_REQUIRED: "Recipient id is required",
  EXCHANGE_CURRENCY_ID: "Exchange currency id is required",
  AMOUNT_REQUIRED: "Amount is required",
  ENABLED_REQUIRED: "Enabled is required",
  ENABLED_INVALID: "Enabled must be a true/false",
  FACTOR_REQUIRED: "Factor is required",
  FACTOR_INVALID: "Value must be a number between 0 and 100",
  COIN_UUID_REQUIRED: "Coin uuid is required",
  BALANCE_REQUIRED: "Balance is required",
  BALANCE_INVALID: "Balance must be greater than 0",
  SIDE_REQUIRED: "Side is required",
  SIDE_INVALID: "Invalid side",
  SIDE_INCLUDES: ["buy", "sell", "withdraw", "deposit"],
  PAGE_REQUIRED: "Page is required",
  PAGE_INVALID: "Page must be a positive number.",
  OFFSET_REQUIRED: "Offset is required",
  OFFSET_INVALID: "Offset must be a positive number.",
  DEPOSIT_ID_REQUIRED: "Deposit id is required",
  EMAIL_TYPE_REQUIRED: "Email type is required",
  EMAIL_TYPE_INVALID: "Email type is invalid",
  NOTES_REQUIRED: "Notes are required",
  VIDEO_LINK_REQUIRED: "Video link is required",
  USER_ID_REQUIRED: "User id is required",
  STATUS_REQUIRED: "Status is required",
  STATUS_INVALID: "Status must be a true/false",
  USER_STATUS_INVALID: "Invalid status. Allowed values are recover or suspend.",
  TRANSACTION_STATUS_INVALID:
    "Invalid status. Allowed values are approved or rejected.",
  SUSPENDED_STATUS_REQUIRED: "Suspended status is required",

  WITHDRAWS_REQUIRED: "Withdraws is required",
  BSB_REQUIRED: "BSB is required",
  BSB_INVALID: "Maximum 7 characters allowed",
  ACCOUNT_NUMBER_REQUIRED: "Account number is required",
  ACCOUNT_NUMBER_INVALID_LENGTH: "Maximum 20 characters allowed",
  FEE_REQUIRED: "Fee is required",
  WALLET_ID_REQUIRED: "Wallet id is required",
  AMOUNT_HUNDRED_INVALID: "Amount must be greater than or equal to 100",
  REFERENCE_ID_REQUIRED: "Reference id is required",
  REFERENCE_ID_INVALID_LENGTH: "Maximum 18 characters allowed",
  WITHDRAW_ID_REQUIRED: "Withdraw id is required",
  TOKEN_REQUIRED: "Token is required",
  TOKEN_INVALID: "Invalid token",
  EVENT_URL_REQUIRED: "Event url is required",
  HASH_REQUIRED: "Hash is required",
  PASSWORD_REQUIRED: "Password is required",
  CURRENT_PASSWORD_REQUIRED: "Current password is required",
  CONFIRM_PASSWORD_REQUIRED: "Confirm password is required",
  PASSWORDS_MISMATCH: "Passwords don't match",
  EMAIL_NOTIFICATION_REQUIRED: "Email notification is required",
  EMAIL_NOTIFICATION_INVALID: "Email notification must be a boolean value",
  NAME_REQUIRED: "Name is required",
  NAME_INVALID_LENGTH: "Maximum 30 characters allowed",
  API_KEY_REQUIRED: "API key generate flag is required",
  API_KEY_INVALID: "API key generate flag must be a boolean value",
  VERIFICATION_CODE_REQUIRED: "QR verification code is required",
  LOGIN_KEY_REQUIRED: "Login key is required",
  LOGIN_KEY_INVALID: "Login key is invalid",
  CONSENT_REQUIRED: "Consent is required",
  EMAIL_TOKEN_REQUIRED: "Email token is required",
  BANK_ACCOUNT_NUMBER_REQUIRED: "Bank Account No is required",
  BANK_ACCOUNT_TITLE_REQUIRED: "Bank Account Title is required",
  AMOUNT_ZERO_INVALID: "Amount must be greater than 0",
  COIN_ID_REQUIRED: "Coin id is required",
  QUANTITY_REQUIRED: "Quantity is required",
  QUANTITY_INVALID: "Maximum 8 decimal places are allowed for quantity",
  BUY_AMOUNT_INVALID: "Maximum 2 decimal places are allowed for amount",
  WALLET_ADDRESS_REQUIRED: "Wallet address is required",
  ACTION_REQUIRED: "Action is required",
  ACTION_INVALID: "Action Invalid",
  UPDATE_BUY_ASSET_INCLUDES: ["approved", "rejected"],
  UPDATE_DEPOSIT_INCLUDES: ["approved", "rejected"],
  FIREBLOCK_INCLUDES: ["REJECTED", "COMPLETED"],
  PASSWORD_LENGTH_INVALID: "Password must be between 8-40 characters long",
  WALLET_TYPE_REQUIRED: "Wallet type is required",
  AMOUNT_MIN_10: "Amount must be equal or greater than 10",
  FEE_RANGE: "Fee must be between 0-100",
  NOTE_REQUIRED: "Note is required",
  LINK_REQUIRED: "Link is required",
};

exports.keys = {
  FIRST_NAME: "firstName",
  LAST_NAME: "lastName",
  EMAIL: "email",
  DOB: "dob",
  CAPTCHA_TOKEN: "captchaToken",
  FEE: "fee",
  //////////////
  ID: "id",
  ENABLED: "enabled",
  FACTOR: "factor",
  UUID: "uuid",
  BALANCE: "balance",
  SIDE: "side",
  PAGE: "page",
  OFFSET: "offset",
  STATUS: "status",
  DEPOSIT_ID: "depositId",
  TYPE: "type",
  NOTES: "notes",
  VIDEO_LINK: "videoLink",
  USER_ID: "userId",
  DISABLED: "disabled",
  SUSPENDED: "suspended",
  CONTACT_EMAIL: "contactEmail",
  WITHDRAWS: "withdraws",
  WITHDRAWS_USERID: "withdraws.*.userId",
  WITHDRAWS_BSB: "withdraws.*.bsb",
  WITHDRAWS_ACCOUNT_NUMBER: "withdraws.*.accountNumber",
  WITHDRAWS_AMOUNT: "withdraws.*.amount",
  WITHDRAWS_REFID: "withdraws.*.refId",
  WITHDRAWS_ID: "withdraws.*.id",
  WITHDRAWS_STATUS: "withdraws.*.status",
  TOKEN: "token",
  EVENT_URL: "eventUrl",
  HASH: "hash",
  PASSWORD: "password",
  CURRENT_PASSWORD: "currentPassword",
  CONFIRM_PASSWORD: "confirmPassword",
  EMAIL_NOTIFICATION: "emailNotification",
  ACTIVE: "active",
  NAME: "name",
  KEY: "key",
  VERIFICATION_CODE: "verificationCode",
  LOGIN_KEY: "loginKey",
  CONSENT: "consent",
  EMAIL_TOKEN: "emailToken",
  BSB: "bsb",
  BANK_ACCOUNT_NUMBER: "bankAccountNumber",
  BANK_ACCOUNT_TITLE: "bankAccountTitle",
  ACCOUNT_NUMBER: "accountNumber",
  ACCOUNT_TITLE: "accountTitle",
  AMOUNT: "amount",
  WALLET_ID: "walletId",
  COIN_ID: "coinId",
  QUANTITY: "quantity",
  WALLET_ADDRESS: "walletAddress",
  ROLE: "role",
  SOURCE_CURRENCY: "sourceCurrency",
  DESTINATION_CURRENCY: "destinationCurrency",
  RECIPIENT_ID: "recipientId",
  EXCHANGE_CURRENCY_ID: "exchangeCurrencyId",
  NOTE: "note",
  LINK: "link",
};

exports.generic = {
  YEARS: "years",
};

exports.UserStatuses = ["recover", "suspend"];

exports.TransactionStatuses = ["approved", "rejected"];
